// vue3/todo-list/src/App.vue
<template>
  <div id="app">
     <div class="page-content page-container" id="page-content">
        <div class="padding">
          <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
              <div class="card px-3">
                <div class="card-body">
                  <h4 class="card-title">Awesome Todo list</h4>
                  <div class="add-items d-flex">
                    <input
                      type="text"
                      v-model="newTaskTitle"
                      class="form-control todo-list-input"
                      placeholder="What do you need to do today?"
                    />
                    <button class="add btn btn-primary font-weight-bold todo-list-add-btn" @click="addItem">
                      Add
                    </button>
                  </div>
                  <div class="list-wrapper">
                    <ul class="d-flex flex-column-reverse todo-list">
                      <TaskItem 
                        v-for="(item,index) in tasks" :key="index" 
                        :title="item.title" :done="item.done" 
                        @change="changeItem(index)"
                        @remove="removeItem(index)"
                      />
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</template>

<script>
import TaskItem from '@/components/TaskItem'
import {ref, reactive} from '@vue/composition-api'
export default {
  name: 'App',
  setup(){
    let newTaskTitle = ref("")
    let tasks = reactive([
      {title: "Tarea 1", done: false},
      {title: "Tarea 2", done: true},
      {title: "Tarea 3", done: false}
    ])

    function changeItem(index){
      tasks[index].done = !tasks[index].done
    }

    function removeItem(index){
      tasks.splice(index,1)
    }

    function addItem(){
      let newTask = {
        title: newTaskTitle.value,
        done: false
      }
      tasks.push(newTask)
      newTaskTitle.value = ""
    }

    return {
      tasks,
      newTaskTitle,
      addItem,
      changeItem,
      removeItem
    }
  },
  components:{
    TaskItem
  }
}
</script>

// angular/angular-todo/src/app/app.component.ts
import { Component } from '@angular/core';
import { TaskItem } from 'src/model/TaskItem';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  newTaskTitle: string
  tasks:TaskItem[] = [
    { title: "Tarea 1", done: false},
    { title: "Tarea 2", done: true},
    { title: "Tarea 3", done: false},
  ]

  addTask(){
    let newTask = {title: this.newTaskTitle, done: false}
    this.tasks.push(newTask)
    this.newTaskTitle = ""
  }

  changeTask(index) {
    this.tasks[index].done = !this.tasks[index].done
  }
  removeTask(index){
    this.tasks.splice(index,1)
  }
}

<div class="page-content page-container" id="page-content">
  <div class="padding">
    <div class="row container d-flex justify-content-center">
      <div class="col-lg-12">
        <div class="card px-3">
          <div class="card-body">
            <h4 class="card-title">Awesome Todo list</h4>
            <div class="add-items d-flex">
              <input
                type="text"
                [(ngModel)] = "newTaskTitle"
                class="form-control todo-list-input"
                placeholder="What do you need to do today?"
              />
              <button (click)="addTask()"
                class="add btn btn-primary font-weight-bold todo-list-add-btn"
              >
                Add
              </button>
            </div>
            <div class="list-wrapper">
              <ul class="d-flex flex-column-reverse todo-list">
                <app-task-item *ngFor="let item of tasks; let i = index"
                [title] = "item.title" [done]="item.done"
                (change)="changeTask(i)" 
                (remove)="removeTask(i)"
                >

                </app-task-item>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
