// vue3/todo-list/src/components/TaskItem.vue
<template>
    <li :class="{completed: done}">
        <a href="#" class="form-check" @click="change">
            {{title}}
        </a>
        <i class="remove mdi mdi-close-circle-outline" @click="remove"></i>
    </li>
</template>

<script>
export default {
    name: "TaskItem",
    props: ["title", "done"],
    setup(props,context){

        function change(){
            context.emit("change")
        }

        function remove(){
            context.emit("remove")
        }

        return {
            change,
            remove
        }
    }
}
</script>

// react/todo-list/src/components/TaskItem.js
import React from "react"

function TaskItem(props){
	return (
    <li className={props.done? "completed": ""}>
      <a href="#" className="form-check" onClick={props.onChange}>
       {props.title}
      </a>
      <i className="remove mdi mdi-close-circle-outline" onClick={props.onRemove}></i>
    </li>
  );
}

export default TaskItem
