// vue3/todo-list/src/components/TaskItem.vue
<template>
    <li :class="{completed: done}">
        <a href="#" class="form-check" @click="change">
            {{title}}
        </a>
        <i class="remove mdi mdi-close-circle-outline" @click="remove"></i>
    </li>
</template>

<script>
export default {
    name: "TaskItem",
    props: ["title", "done"],
    setup(props,context){

        function change(){
            context.emit("change")
        }

        function remove(){
            context.emit("remove")
        }

        return {
            change,
            remove
        }
    }
}
</script>

// angular/angular-todo/src/app/task-item/task-item.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-task-item',
  templateUrl: './task-item.component.html',
  styleUrls: ['./task-item.component.css']
})
export class TaskItemComponent implements OnInit {

  constructor() { }
  @Input("title")  title: string;
  @Input("done") done: boolean

  @Output() change:EventEmitter<any> = new EventEmitter()
  @Output() remove:EventEmitter<any> = new EventEmitter()
  ngOnInit(): void {
  }

}

<li [ngClass]="{ completed: done }">
  <a href="#" class="form-check" (click)="change.emit()" >
    {{ title }}
  </a>
  <i class="remove mdi mdi-close-circle-outline" (click)="remove.emit()"></i>
</li>
